### ISSUE TITLE
Designers to clarify

### ISSUE THREAD

**Issue by emmamarichal** [DylanYoungKoto/FacultyGlyphic#3]
Hi @DylanYoungKoto!

I saw you added your designer profile thanks to the form (with **Koto Studio**).

I would need to clarify who are the designers credited for this project. There can be several, no problem, but the list has to be the same everywhere:
- In the sources (in the `designer` field, in `font infos`)
- In the `AUTHORS.txt` in the repo
- In the metadata.pb in `https://github.com/google/fonts/tree/main/ofl/facultyglyphic`  (I do it)
- When you fill out the form, you have to do it as many time as there are designers on the list, one for each of them.

This list will be the one that appear on the 'About' section, on Google Fonts. 

I'm asking this, because:
- in FacultyGlyphic.glyphspackage fonts infos, I see "Dylan Young"
- in AUTHORS.txt I see "Dylan Young" and "Koto Studio"
- you filled the form with "Koto Studio"

What should I keep?
Thank you :)

**Comment by DylanYoungKoto** [comment]
Hi @emmamarichal, sorry for the confusion! The designer should be listed as only Koto Studio on the Google Fonts page. 

Is it possible to include Dylan Young in the designer section within the Glyphs file still? I noticed this was how Space Mono was formatted. If it's not possible, please just use Koto Studio.

<img width="1067" alt="Screenshot 2024-10-21 at 09 04 15" src="https://github.com/user-attachments/assets/c96cb9b9-c101-4361-8658-435d5ae727fa">
<img width="1110" alt="Screenshot 2024-10-21 at 09 04 30" src="https://github.com/user-attachments/assets/925e73ea-c0b7-4956-ab44-cf0a0e2f75bd">


I'll be providing the rest of the requirements asap! 

Thanks again!

**Comment by emmamarichal** [comment]
@DylanYoungKoto,

Yes sure! And for Dylan Young, should I move it in the "contributors.txt", in the repo?

**Comment by DylanYoungKoto** [comment]
Yes please, thank you!
